package com.cgs.currency.sql.constants;

public class GlobalCurrencySqlConstants {

	public static final String GLOBAL_CURRENCY_WAITING_FOR_AUTHORIZE_QUERY =" SELECT GLOBAL_CURRENCY_ID, CURRENCY_DESC,CURRENCY_CODE,"
			+ "DECODE(CURRENCY_STATUS,'1','ACTIVE','0','IN ACTIVE') AS CURRENCY_STATUS,"
			+ " DECODE(AUTH_CODE,'0','WAITING FOR AUTHORIZE','1','AUTHORIZED','9','REJECTED')AS AUTH_CODE, ADDED_BY,REMARKS"
			+ " FROM  GLOBAL_CURRENCY WHERE ADDED_BY!='SUPERADMIN2' AND AUTH_CODE='0'OR AUTH_CODE IS NULL  ";

}
